id: P010435
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD363
  title: བོད་བྱང་ཐང་གི་ལྡེའུ།
  author: ''
  volumes:
    d9dcb4cd211447e1b4b33aa4ada64377:
      image_group_id: I2PD17845
      title: ''
      volume_number: 1
      total_pages: 126
