id: P010435
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:49:44.548104
source_metadata:
  id: bdr:W3PD363
  title: བོད་བྱང་ཐང་གི་ལྡེའུ།
  author: ''
  volumes:
    d9dcb4cd211447e1b4b33aa4ada64377:
      image_group_id: I2PD17845
      title: ''
      volume_number: 1
      total_pages: 126
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
